export default {
    install(Vue, options) {
        Vue.prototype.$localization = {
            de: {
                bbaw: 'Berlin-Brandenburgische Akademie der Wissenschaften',

                about_header: 'Impressum',
                about_published_by: 'Veröffentlicht von',
                about_represented_by: 'Vertreten durch',
                about_legal_status: 'Rechtstatus',
                about_legal_entity: 'Rechtsfähige Körperschaft öffentlichen Rechts',
                about_vat: 'Umsatzsteuer-Identifikationsnummer',
                about_vat_note: 'gemäß §27 a des Mehrwertsteuergesetzes der Bundesrepublik Deutschland',
                about_technical: 'Technische Umsetzung',

                license_header: 'Lizenzhinweise',
                license_note: 'Bitte beachten Sie unsere Lizenzhinweise',
                license_rd: 'Forschungsdaten',
                license_sw: 'Software',
                license_text: 'Die PIR App ist Open Source Software veröffentlicht unter der',
                license_available: 'Quellcode veröffentlicht auf ',
                license_author: 'Autor',

                consent_note: 'Wir nutzen Cookies zur Verbesserung unseres Webangebots. Nähreres entnehmen Sie bitte unserer ',
                consent_declaration: 'Datenschutzerklärung',

                accept: 'Akzeptieren',
                decline: 'Ablehnen',

                contactperson: 'Ansprechpartner',
                processing: 'Ihre Anfrage wird ausgeführt ...',
                result_none: 'Keine Treffer für Ihre Anfrage',
                records: 'Einträge',
                records_for: 'Treffer für',
                search: 'Suche',
                search_reset: 'Suchparameter zurücksetzen',

                search_string: 'Suchbegriff(e)',
                search_resource: 'Suche in',
                search_resource_keywords: 'Stichwortliste',
                search_resource_addenda: 'Addenda',
                search_connector: 'Logischer Operator',
                search_connector_or: 'ODER',
                search_connector_and: 'UND',
                search_case: 'Groß-Kleinschreibung beachten',
                search_case_sensitive: 'Ja',
                search_case_insensitive: 'Nein',
                search_gender: 'Geschlecht',
                search_gender_all: 'Alle',
                search_gender_female: 'Weiblich',
                search_gender_male: 'Männlich',
                search_gender_notKnown: 'Unbekannt',
                search_gender_total: 'Alle',
                search_class: 'Soziale Gruppe',
                search_class_all: 'Alle',
                search_class_normal: 'Normal',
                search_class_eques: 'equester ordo',
                search_class_senator: 'ordo senatorius',
                search_class_total: 'Alle',

                nav_search: 'Suche',
                nav_overview: 'Überblick',
                nav_publications: 'Publikationen',
                nav_methods: 'Arbeitsweise',
                nav_history: 'Geschichte',
                nav_resources: 'Ressourcen',
                nav_api: 'API',

                cite_item: 'Permalink',
                cite_date: 'abgerufen am',
                clipboard_copy: 'In die Zwischenablage kopieren',
                clipboard_copied: 'Der Wert wurde in die Zwischenablage kopiert',

                reference: 'Referenz',
                add_tribe: 'Gens',
                add_origin: 'Herkunft',
                add_lifespan: 'Lebenszeit',
                add_career: 'Ämter',
                add_occupations: 'Sonstige Tätigkeiten',
                add_relatives: 'Verwandtschaft',
                add_article: 'Artikel',
                add_sources: 'Quellen',
                add_literature: 'Literatur',
                add_notes: 'Anmerkungen',
            },
            en: {
                bbaw: 'Berlin-Brandenburg Academy of Sciences and Humanities',

                about_header: 'Imprint',
                about_published_by: 'Published by',
                about_represented_by: 'Represented by',
                about_legal_status: 'Legal Status',
                about_legal_entity: 'public law legal entity',
                about_vat: 'VAT Identification Nr.',
                about_vat_note: 'according to §27 a of the Value Added Tax Law of the Federal Republic of Germany',
                about_technical: 'Technical realisation',

                license_header: 'Copyright',
                license_note: 'Please note our copyright remarks',
                license_rd: 'Research Data',
                license_sw: 'Software',
                license_text: 'The PIR App is open-sourced software licensed under the',
                license_available: 'Code available on ',
                license_author: 'Author',

                consent_note: 'We are using cookies to enhance our service. Further information in our ',
                consent_declaration: 'privacy policy',

                accept: 'Accept',
                decline: 'Decline',

                contactperson: 'Contact',
                processing: 'Processing Your request ...',
                result_none: 'No matching record',
                records: 'records',
                records_for: 'matching records for',
                search: 'search',
                search_reset: 'reset search parameters',

                search_string: 'Search string(s)',
                search_resource: 'Searching in',
                search_resource_keywords: 'Keywords',
                search_resource_addenda: 'Addenda',
                search_connector: 'Logical Operator',
                search_connector_or: 'OR',
                search_connector_and: 'AND',
                search_case: 'Case sensitivity',
                search_case_sensitive: 'case-sensitive',
                search_case_insensitive: 'case-insensitive',
                search_gender: 'Gender',
                search_gender_all: 'All',
                search_gender_female: 'Female',
                search_gender_male: 'Male',
                search_gender_notKnown: 'Not known',
                search_gender_total: 'All',
                search_class: 'Social Class',
                search_class_all: 'All',
                search_class_normal: 'Normal',
                search_class_eques: 'equester ordo',
                search_class_senator: 'ordo senatorius',
                search_gender_total: 'All',

                nav_search: 'Search',
                nav_overview: 'Overview',
                nav_publications: 'Publications',
                nav_methods: 'Methods',
                nav_history: 'History',
                nav_resources: 'Resources',
                nav_api: 'API',

                cite_item: 'Perma Link',
                cite_date: 'downloaded at',
                clipboard_copy: 'Copy to clipboard',
                clipboard_copied: 'Value was copied to clipboard',

                reference: 'Reference',
                add_tribe: 'Tribe',
                add_origin: 'Origin',
                add_lifespan: 'Lifespan',
                add_career: 'Career',
                add_occupations: 'Other occupations',
                add_relatives: 'Relatives',
                add_article: 'Article',
                add_sources: 'Career',
                add_sources: 'Sources',
                add_literature: 'Literature',
                add_notes: 'Notes',
            }
        }
    }
}
